version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: saha-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saha1234  # 팀 공용 비번
      POSTGRES_DB: saha_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data